CREATE DATABASE SQLCOMMANDS
USE SQLCOMMANDS

CREATE TABLE GROUPS(
ID INT PRIMARY KEY IDENTITY,
[NAME] NVARCHAR(50) UNIQUE,
GROUPCOUNT INT
)
Insert Into GROUPS Values('bp22',22)
INSERT INTO GROUPS VALUES('BP201',16)
INSERT INTO GROUPS VALUES('BP202',18)
SELECT*FROM GROUPS



DELETE FROM GROUPS WHERE ID=6

UPDATE GROUPS
SET NAME='BP210',GROUPCOUNT=30
WHERE ID=3
